# Generated by Django 2.2.1 on 2019-06-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.IntegerField()),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=128)),
                ('team2', models.CharField(max_length=128)),
                ('toss_winner', models.CharField(max_length=128)),
                ('toss_decision', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=128)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(max_length=128, null=True)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=128, null=True)),
                ('venue', models.CharField(max_length=128)),
                ('umpire1', models.CharField(max_length=128)),
                ('unpire2', models.CharField(max_length=128)),
                ('unpire3', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
