# Generated by Django 2.2.1 on 2019-06-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='unpire3',
            new_name='umpire2',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='unpire2',
        ),
        migrations.AddField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Deliviers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match1_id', models.IntegerField()),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(max_length=128)),
                ('bowling_team', models.CharField(max_length=128)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=128)),
                ('non_striker', models.CharField(max_length=128)),
                ('bowler', models.CharField(max_length=128)),
                ('is_super_over', models.IntegerField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(max_length=128, null=True)),
                ('dismissal_kind', models.CharField(max_length=128, null=True)),
                ('fielder', models.CharField(max_length=128, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.Matches')),
            ],
        ),
    ]
