# Generated by Django 2.2.1 on 2019-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0003_auto_20190617_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateField(),
        ),
    ]
